name       : libnetfilter-queue
version    : 1.0.3
release    : 1
source     :
    - https://netfilter.org/projects/libnetfilter_queue/files/libnetfilter_queue-1.0.3.tar.bz2 : 9859266b349d74c5b1fdd59177d3427b3724cd72a97c49cc2fffe3b55da8e774
license    : GPL-2.0
component  : programming.library
summary    : libnetfilter_queue is a userspace library providing an API to packets that have been queued by the kernel packet filter.
description: |
    libnetfilter_queue is a userspace library providing an API to packets that have been queued by the kernel packet filter.
    It is is part of a system that deprecates the old ip_queue / libipq mechanism.
    libnetfilter_queue has been previously known as libnfnetlink_queue.
builddeps  :
    - pkgconfig(libmnl)
    - pkgconfig(libnfnetlink)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
